name: yaoyao-funcs

services:
  yaoyaoapi:
    build: .
    container_name: yaoyaoapi
    restart: always
    ports:
      - 8080:8080
    env_file:
      - .env
    depends_on:
      - yaoyaodb
    networks:
      - yaoyao-network
    volumes:
      - .:/app
      - go-build-cache:/root/.cache/go-build
      - go-mod-cache:/go/pkg/mod

  yaoyaodb:
    image: postgres:17
    container_name: yaoyaodb
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: yaoyaodb
    ports:
      - 5432:5432
    volumes:
      - ./data/db:/data/db
    networks:
      - yaoyao-network
networks:
  yaoyao-network:
    driver: bridge
volumes:
  yaoyao-volume:
  go-build-cache:
  go-mod-cache:
